#!/bin/sh

add_torrent() {
    transmission-remote -a ${@:-"`xsel -o`"}
}

parse_git_branch(){
    git rev-parse --abbrev-ref HEAD
}

parse_git_upstream() {
    git rev-list --count `git for-each-ref --format='%(upstream:short)'`..HEAD
}

parse_svn_rev(){
    svn info | sed -n 's/Revision: //p';
}

mkcd() {
    mkdir -p $1 && cd $1
}

backup() {
    for i in $@; do
        cp -- "$i{,~}"
    done
}

venv() {
    venv_dir=$HOME/.venv
    if [ ! x"" = x"$P_VENV_DIR" ]; then
        venv_dir=$P_VENV_DIR
    fi

    if [ ! -e $venv_dir/$1 ]; then
        (
            cd $venv_dir
            virtualenv $@
        )
    fi

    if [ ! -d $venv_dir/$1 ]; then
        echo $venv_dir/$1 already exists and is not a directory
        return 1
    fi

    source $venv_dir/$1/bin/activate
}

termite_change_color() {
    termite_dir="${XDG_CONFIG_HOME:-$HOME/.config}/termite"
    termite_col="$1"

    [ $# -gt 1 ] && echo "Usage: ${0##*/} COLOR" && return

    if [ $# -eq 1 ] && [ ! -r "${termite_dir}/${termite_col}" ]; then
        echo "${termite_dir}/${termite_col} cannot be read."
        echo "Usage: ${0##*/} COLOR"
        return
    fi

    cat "${termite_dir}/base" > "${termite_dir}/config"
    [ -f "${termite_dir}/${termite_col}" ] && \
        cat "${termite_dir}/${termite_col}" >> "${termite_dir}/config"
}

gen_password() {
    cat /dev/urandom | base64 | head -c ${1:-8}
}
