#!/bin/sh

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    [ -r ~/.dircolors ] \
                && eval "$(dircolors -b ~/.dir_colors)"\
                || eval "$(dircolors -b)"
    alias ls="ls -h --color=auto"
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias diff='colordiff -EZbwBt'
fi

[ -r $HOME/.lynx.lss ] &&  alias lynx="lynx -lss=$HOME/.lynx.lss"

# ls tweaks direcory contents
alias lsa='ls -lah'
alias l='ls -l'
alias ll='ls -l'
alias la='ls -lA'
alias sl=ls # often screw this up

# Push and pop directories on directory stack
alias pu='pushd'
alias po='popd'

alias c="clear"
alias claer='clear'

# Super user
alias _='sudo'

alias afind='ack-grep -il'

alias ping='ping -c5'

alias asdfg="setxkbmap $PRAJJ_XKB_OPTS"
