#!/bin/sh

function mkcd() {
    mkdir -p $1 && cd $1
}

function backup() {
    for i in $@; do
        cp $i{,~}
    done
}

function toggleTouchpad() {
    device=xinput --list | awk '/GlidePoint/ { sub(/id=/,""); print $6}'
    case $1 in
        enable|on|"1") xinput enable $device
            ;;
        disable|off|"0") xinput disable $device
            ;;
        *) echo "on OR off" >&2
            ;;
    esac
}


function termite_color() {
    FUNC_TERMITE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/termite"
    [ $1 ] && FUNC_TERMITE_COL="$1"

    if [ -r "${FUNC_TERMITE_DIR}/${FUNC_TERMITE_COL}" ]; then
        cat "${FUNC_TERMITE_DIR}/base" "${FUNC_TERMITE_DIR}/${FUNC_TERMITE_COL}"\
            > "${FUNC_TERMITE_DIR}/config"
    fi
}

