#!/bin/sh

parse_git_branch(){
    git rev-parse --abbrev-ref HEAD
}

parse_git_upstream() {
    git rev-list --count `git for-each-ref --format='%(upstream:short)'`..HEAD
}

parse_svn_rev(){
    svn info | sed -n 's/Revision: //p';
}

mkcd() {
    mkdir -p $1 && cd $1
}

backup() {
    for i in $@; do
        cp -- "$i{,~}"
    done
}

toggleTouchpad() {
    device="$(xinput --list | sed -n '/GlidePoint/s/.*id=\([0-9]\+\).*/\1/p')"
    case $1 in
        enable|on|"1") xinput enable $device
            ;;
        disable|off|"0") xinput disable $device
            ;;
        *) echo "on OR off" >&2
            ;;
    esac
}

function termite_color() {
    FUNC_TERMITE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/termite"
    [ $1 ] && FUNC_TERMITE_COL="$1"

    if [ -r "${FUNC_TERMITE_DIR}/${FUNC_TERMITE_COL}" ]; then
        cat "${FUNC_TERMITE_DIR}/base" "${FUNC_TERMITE_DIR}/${FUNC_TERMITE_COL}"\
            > "${FUNC_TERMITE_DIR}/config"
    fi
}
