#!/bin/sh

function mkcd() {
    mkdir -p $1
    cd $1
}

function backup() {
    for i in $@; do
        cp $i{,~}
    done
}

function toggleTouchpad() {
    device=xinput --list | awk '/GlidePoint/ { sub(/id=/,""); print $6}'
    case $1 in
        enable|on|"1") xinput enable $device
            ;;
        disable|off|"0") xinput disable $device
            ;;
        *) echo "on OR off" >&2
            ;;
    esac
}


function termite_color() {
    __TERMITE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/termite"
    [ $1 ] && __TERMITE_COL="$1"

    if [ -r "${__TERMITE_DIR}/${__TERMITE_COL}" ]; then
        cat "${__TERMITE_DIR}/base" "${__TERMITE_DIR}/${__TERMITE_COL}"\
            > "${__TERMITE_DIR}/config"
    fi
}

