#!/bin/bash

mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/backups # TODO: change backups to undodir
curl -Sso ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
echo "The rest of this script doesn't exactly work. Exiting"
exit

cd ~/.vim/bundle/
git clone git@github.com/tpope/vim-sensible.git
git clone git@github.com/tpope/vim-classpath.git
git clone git@github.com/tpope/vim-scriptease.git
git clone git@github.com/tpope/vim-surround.git
git clone git@github.com/tpope/vim-fugitive.git
git clone git@github.com:scrooloose/syntastic.git
git clone git@github.com:altercation/vim-colors-solarized.git
git clone git@github.com:tpope/vim-unimpaired.git
git clone git@github.com:tpope/vim-commentary.git
git clone git@github.com:tpope/vim-abolish.git
git clone git@github.com:tpope/vim-repeat.git
git clone git@github.com:scrooloose/nerdtree.git
git clone git@github.com:scrooloose/nerdcommenter.git
git clone git@github.com:tomasr/molokai.git
git clone git@github.com:Lokaltog/vim-powerline.git
git clone git@github.com:SirVer/ultisnips.git
git clone git@github.com:godlygeek/tabular.git
git clone git@github.com:editorconfig/editorconfig-vim.git
git clone git@github.com:stephenmckinney/vim-solarized-powerline.git
