#!/bin/sh

killall conky &
conky -c '/home/pbhandari/.conky/clock/conkyrc' &
conky -c '/home/pbhandari/.conky/sys/conkyrc' &
conky -c '/home/pbhandari/.conky/mpd/conkyrc' &

nitrogen --restore &

[ `pgrep xbindkeys` ] || xbindkeys &

urxvt -name Urxvt-soc -e tmux new -As social &

[ `pgrep clipit` ] || clipit & sleep 2s

[ `pgrep batti` ] || batti & sleep 2s

[ `pgrep stalonetray` ] || stalonetray & sleep 2s

pidign &
